src/Components/DataDisplay/Tab.vue
Tab을 변경했습니다.기존에 props를 직접 변경하는 anti-pattern에서 벗어나서, event를 emit하고 상위 컴포넌트에서 나머지 로직을 처리하도록 했습니다.
=> [change] Tab

assets/style/base/mixins.scss, assets/style/base/utils.scss, src/Components/Button/Button.vue, src/Components/Message/Modal.vue, src/DataEntry/Input.vue, src/Elements/Core/Icon/Icon.vue
* [add] Icon 배경색 투명색
* [fix] Input style 수정
* [add] disabled mixin
* [add] Button loading일 때 커서 동작 안하도록
* [add] Modal에 버튼 로딩 추가
=> Feature/add button loading (#23)

package.json, yarn.lock
- 프로젝트 메인에 올라갈 공식 docs를 deploy하는 스크립트입니다.
- chromatic은 ui visual test용으로 쓰면 됩니다.
=> [add] ghpages에 storybook을 deploy하는 script 추가

src/Components/Button/Button.vue, src/Components/Message/Toast.vue, src/Components/Message/index.js, stories/Toast/Toast.stories.js
toast component를 추가 했습니다.
+ button success, primary 의 outlined, disabled style 추가
=> [add] toastComponent

src/Components/Message/Modal.vue, stories/Modal/Modal.stories.js
- placeholder를 props로 변경
- formValidator를 Function type props로 변경해 유연하게 활용
=> [change] Modal placeholder props & formValidator props

package.json, yarn.lock
- commit할 때 stage된 파일만 lint를 적용하도록
=> [add] husky && lint-staged

src/DataEntry/SearchInput.vue
icon validator때문에 color를 primary->green600으로 변경
=> [fix] Icon color

src/DataEntry/Input.vue
- input placeholder gray300 body1 적용
=> [change] input placeholder 스타일 수정

src/Components/DataDisplay/Avatar.vue
변경사항
- right-icon 추가
- text color를 props로 받도록 변경
=> [change] avatar text v-html로 변경 및 textColor 추가

.github/workflows/build-test.yml, .github/workflows/chromatic.yml
PR을 open하면 해당 버전의 스토리북을 chromatic에 배포합니다.
+ build test도 추가하였습니다. 가끔 릴리즈할 때 에러뜨는 경우가 있어서 확실히 잡고가기 위함입니다.
=> [add] githubAction deploy versioned chromatic

__test__/Button.test.js, jest.config.js, package.json, yarn.lock
- jest 추가
- jest 스크립트 추가
- jest example test code 추가
=> [add] Jest & Jest scripts & Jest example test code

src/Components/Message/Modal/index.js, src/Components/Message/index.js
Modal을 다 만들어놓고 컴포넌트로 등록하는 것을 깜빡했읍니다...^_ㅠ
=> [add] modal import

src/Components/Button/Button.vue
Button에서 hover, loading이 겹치는 순간의 style 오류를 수정했습니다.
=> [fix] Button loading style

assets/images/icon/icon-check-large-line.svg, assets/images/icon/icon-download-large-line.svg, src/Elements/Core/Icon/Icon.vue, stories/Icon/Icon.stories.js, stories/Icon/Icon.stories.mdx
=> [add] icon large type (IconDownloadLargeLine, IconCheckLargeLine)

src/Components/Button/LinkButton.vue
blue600 고정 -> blue600, blue400을 사용하도록 변경
=> [change] LinkButton color

src/Components/Button/Button.vue, stories/Button/Button.stories.mdx
- Icon Size에 따른 여백 변경 (2px, 4px)
- Button With Icon docs 추가
- icon className 변경(_ -> --)
- hover green color 오류 수정
- xlarge style 변경
- textType error hover 색상 변경 (red100 -> red000) (디자이너 요청)
=> Button 컴포넌트 변경, Docs With Icon 추가

src/Components/Button/NarrowButton.vue
=> [remove] NarrowButton min-width 제거

assets/style/base/animation.scss, src/DataDisplay/BottomDrawer.vue, src/DataDisplay/BottomDrawerExample.vue, src/DataDisplay/Drawer.vue, src/DataDisplay/SideDrawer.vue, src/DataDisplay/SideDrawerExample.vue, stories/DataDisplay/BottomDrawer.stories.js, stories/DataDisplay/Drawer.stories.js
=> [add] bottomDrawer component 추가

src/Components/Message/Modal/BasicModal.vue, src/Components/Message/Modal/Modal.vue, src/Components/Message/Modal/WithFormModal.vue
- BasicModal, WithFormModal pc에서 max-height 640px
- WithFormModal contents영역 상위의 Typography 제거
- 스크롤 오버레이는 어려워서 스타일 주석처리
=> [change] Modal pc maxHeight

package.json, src/Elements/Core/Icon/Icon.vue
IE에서는 getElementsByClassName도 안된다네요 ^^ 하하하하
=> Fix: ie issue

src/Components/Message/Modal/BasicModal.vue, src/Components/Message/Modal/FullscreenModal.vue, src/Components/Message/Modal/Modal.vue, src/Components/Message/Modal/PermissionModal.vue, src/Components/Message/Modal/WithFormModal.vue, src/DataEntry/Input.vue, stories/Message/Modal/BasicModal.stories.mdx, stories/Message/Modal/WithFormModal.stories.mdx
- Modal
- padding 0으로 변경
- WithFormModal, BasicModal
- scroll prop, style 추가
- 제목, 컨텐츠, 버튼 영역으로 구분하여 여백 개별 처리 (스크롤바 때문)
- scroll docs 추가
- 전체 모달 컴포넌트에서 contents -> content로 변경
- className 컨벤션에 맞게 변경
- Input align 오류 수정
=> Modal 개선, Input align 오류 수정

src/Components/DataDisplay/Drawer/BottomDrawer.vue, src/Components/DataDisplay/Drawer/BottomDrawerExample.vue, src/Components/DataDisplay/Drawer/Drawer.vue, src/Components/index.js, stories/DataDisplay/BottomDrawer.stories.js, stories/DataDisplay/Drawer.stories.js, stories/DataDisplay/SideDrawer.stories.js
- BottomDrawer
- scroll prop, style 추가
- actionButton, prop 추가
- closeButton style 수정
- DataEntry 컴포넌트 등록
=> BottomDrawer 변경

src/Components/DataEntry/Input.vue
=> Input error 속성과 style 추가

src/Components/Button/Button.vue, stories/Button/Button.stories.mdx
- Button outlined&gray, text에 disabled style이 적용되지 않는 오류 수정
- disabled docs 추가
- disabled일 때, 커서가 안 바뀌는 오류 수정
```
&:disabled {
cursor: not-allowed !important;
&:active {
pointer-events: none;
}
}
```
=> [fix] Button disabled 오류 수정

src/Components/Message/Modal/BasicModal.vue, src/Components/Message/Modal/PermissionModal.vue, src/Components/Message/Modal/WithFormModal.vue
- 모달 아래에 40px 여백 추가
- 스크롤 스타일 수정
=> [change] BasicModal, WithFormModal 구조, style 변경

src/Components/DataEntry/Dropdown.vue, stories/DataEntry/Dropdown.stories.mdx
- 추후 개선할 사항(#127)이 더 있는데, 결제 프로젝트 마감기한때문에 당장 필요한 것만 반영했습니다.
- 영역이 헷갈리는 부분이 있어 주석을 추가하고, 클래스명을 명확하게 변경했습니다.
=> [fix] Dropdown maxHeight 속성 추가, 클래스명 변경

src/Components/Message/Modal/BasicModal.vue, src/Components/Message/Modal/WithFormModal.vue
=> [add] WithFormModal, BasicModal mobile max-height

src/Components/DataEntry/Checkbox.vue, src/Components/Message/Modal/Modal.vue, src/Components/Message/Modal/PermissionModal.vue
- Checkbox checked icon IE에서 안 나오는 오류 수정
- PermissionModal paddingTop 수정(32px -> 24px)
- Modal 닫기버튼 position: fixed 제거 (absolute와 중복됨)
=> 컴포넌트 스타일 수정

.storybook/preview.js, assets/style/base/global.scss, assets/style/base/main.scss, src/main.js
- 공통 스타일, 클래스 -> global.scss
- 변수, 믹스인 -> main.scss
=> [change] 패키지 & 스토리북 css webpack 설정 변경

src/Components/DataEntry/Input.vue, src/Components/DataEntry/InputGroup.vue, src/Components/DataEntry/index.js, src/Components/Message/Modal/WithFormModal.vue, stories/Message/Modal/WithFormModal.stories.mdx
- Input underlined height 변경 (36px -> 40px)
- InputGroup 컴포넌트 추가
- Input + Button을 그룹화하기 위한 컴포넌트입니다.
- Button의 height가 40px이 됩니다.
- WithFormModal docs에 InputGroup 적용
=> InputGroup 추가, WithFormModal docs 변경

mixins/scrollMixin.js, src/Components/DataDisplay/Drawer/BottomDrawer.vue, src/Components/DataDisplay/Drawer/Drawer.vue, src/Components/DataDisplay/Drawer/SideDrawer.vue, src/Components/Message/Modal/Modal.vue
- scrollMixin 추가
- Modal, BottomDrawer, SideDrawer scrollMixin으로 변경
=> overlay영역 스크롤 막는 코드 개선

src/Elements/Core/Logo/Logo.vue, stories/Logo/Logo.stories.mdx
=> Logo 개선, docs 추가

src/Components/DataEntry/InputGroup.vue, stories/DataEntry/InputGroup.stories.js
- Button margin-left 4px 추가
- Docs 추가
=> InputGroup 개선, Docs 추가

assets/style/base/utils.scss, src/Components/DataDisplay/ListItem.vue, stories/DataDisplay/ListItem.stories.mdx
- ListItem cursor 속성 추가
- docs 개선
=> ListItem cursor 추가, docs 개선

src/Components/Button/NarrowButton.vue, stories/Button/NarrowButton.stories.mdx
- size prop 추가
- left-icon, right-icon slot 추가
- docs 개선
=> NarrowButton 개선

src/Elements/Core/Icon/Icon.vue, stories/Icon/Icon.stories.mdx
Story에서 props로 넘길 때 String으로 들어가서 Number로 변환
#41 해결
=> [add] Icon rotation

src/Components/Layout/StyleCol.vue, src/Components/Layout/StyleColGroup.vue, stories/Layout/Layout.stories.js
layout.story.js에 우선 작업했습니다.....
기존의 grid, row, styleCol 파일 확인 및 styleColGroup컴포넌트가 추가되었습니다.
styleColGroup용도는 - styleCol 간격이 일정하게 보이도록 추가한 컴포넌트 입니다
=> [add] styleColGroup 추가 및 grid, row,styleCol 파일 확인

src/Components/DataDisplay/Contents.vue, stories/DataDisplay/Contetns.stories.mdx
contents 컴포넌트 추가
하위요소 slot으로 반영
=> [add] contents

src/Components/Button/LinkButton.vue, stories/Button/LinkButton.stories.mdx
- props 추가: external, nuxt, target
- underline color style 오류 수정
- docs 개선
=> LinkButton Component, Docs 개선

src/Components/DataEntry/Checkbox.vue, stories/DataEntry/Checkbox.stories.mdx
- 웹접근성 대응
- disabled cursor 오류 수정
- color prop 추가
- props validator 추가
=> Checkbox 개선

.github/workflows/test.yml
storybook deployer를 github action으로 변경 -> token을 secrets에서 가져옴으로써 문제 해결 테스트
=> [add] test storybook deployer github action

src/Components/DataDisplay/Avatar.vue
=> Avatar item에 display flex 추가

src/Components/DataEntry/Checkbox.vue, stories/DataEntry/Checkbox.stories.mdx
merge 오류로 원복
* [add] Checkbox typography color
disabled는 gray300, 나머지는 자유
* [fix] Checkbox disabled cursor error
* [add] Checkbox 접근성 대응
* [add] Checkbox props validator
* [fix] Checkbox docs 개선
* [fix] Checkbox focus style error
=> Checkbox 개선 (#164 원복)

src/Components/Button/LinkButton.vue, stories/Button/LinkButton.stories.mdx
- LinkButton type validator TypographyTypes로 변경
- underline style 중첩되는 오류 수정
=> LinkButton type validator 개선, style 오류 수정

src/Components/DataDisplay/List.vue
ListItem의 클래스명을 바꿨는데 List에서 안 바꿔서 오류나서 수정
=> List spacing 오류 수정

src/Elements/Utility/Overlay.vue, stories/Overlay.stories.mdx
- 디자인 완성되지않은 type 제거
- 스토리북 Default 컴포넌트에서 z-index props 추가
=> Overlay 개선

src/Components/Message/Modal/BasicModal.vue, stories/Message/Modal/BasicModal.stories.mdx
- 코드 개선
- props validator 추가
- docs 개선
=> BasicModal 개선

src/Components/Message/Modal/WithFormModal.vue, stories/Message/Modal/WithFormModal.stories.mdx
=> WithFormModal 개선

src/Components/DataDisplay/ChipGroup.vue
=> [fix] chipGroup class, name 수정

src/Components/DataDisplay/Badge.vue, stories/DataDisplay/Badge.stories.mdx
=> Badge 개선, mdx 추가

src/Components/DataDisplay/Drawer/SideDrawer.vue, src/Components/DataDisplay/Drawer/SideDrawerExample.vue, src/Components/Message/Modal/AlertModal.vue, src/Components/Message/Modal/PermissionModal.vue, src/Components/Message/Modal/index.js, stories/Message/Modal/AlertModal.stories.mdx, stories/Message/Modal/PermissionModal.stories.mdx
[fix] permissionModal 수정
[fix] drawer 수정
우선 컴포넌트화 작업 반영내용입니다
=> [add] alertModal

src/Components/DataEntry/Form.vue, src/Components/DataEntry/index.js, stories/DataEntry/Form.stories.mdx
form 안에 있는 data Entry 사이 간격 12px
=> [add] form

src/Components/DataEntry/TextField.vue, stories/DataEntry/Textfield.stories.mdx
=> [fix] textfield 피드백 반영

src/Components/Layout/Grid.vue
=> [fix] nuxt에서 깨짐 개선

src/Components/DataEntry/Dropdown.vue, stories/DataEntry/Dropdown.stories.mdx
Dropdown
- full props 오류 수정
- 스토리북 예시에 인기검색어 라벨 추가
=> Dropdown full 오류 수정, 예시 추가

src/Components/Button/Button.vue, stories/Button/Button.stories.mdx
- button이 disabled면 icon cursor: not-allowed로 변경
- button이 disabled면 icon color를 button color로 변경
- button mdx disabled에 icon 추가
=> Button disabled일 때 icon 색상, 커서 변경

src/Components/Button/Button.vue
반복되는 색상값들을 변수로 치환해봤는데 어떤 방식이 더 좋으신가요?
나중에 유지보수할 때 저값들을 한번에 바꿀땐 변수에서 한번에 바꾸는 게 더 깔끔한거 같아서요.
=> [change] 색상값들을 변수명으로 치환

stories/DataDisplay/ChipGroup.stories.mdx, stories/DataEntry/Dropdown.stories.mdx, stories/DataEntry/Form.stories.mdx, stories/DataEntry/InputGroup.stories.js, stories/Message/Modal/WithFormModal.stories.mdx
v1 변경사항에 대응되지 않은 오류들 수정
- color gray -> secondary
- Input -> TextField
=> 스토리북 v1 변경사항 적용

src/Components/DataEntry/FormGroup.vue, src/Components/DataEntry/TextArea.vue, src/Components/DataEntry/index.js, stories/DataEntry/Form.stories.mdx, stories/DataEntry/FormGroup.stories.mdx
- Textarea type props 변경 (outline -> outlined)
- Form
- 컴포넌트명 변경 (Form -> FormGroup) 
- mdx 변경
- 다른 스토리북 구조와 맞지 않아서 변경함
- textarea props 변경
=> Textarea props, Form 컴포넌트명, mdx 변경

src/Components/DataDisplay/Tabs.vue
Tabs type="swiper"가 기능대로 동작을 안해서, 실제 프로덕트 로컬에서 테스트해보려고 합니다.
=> [add] Tabs test용 배포

stories/DataDisplay/List.stories.mdx
동훈님의 제안으로 List 예시 스토리를 추가했습니다.
=> [add] List mdx example

.github/workflows/chromatic-develop.yml
release -> master에서도 발동하게 했습니다.
=> [change] chromatic github action master에도 추가

src/Components/DataEntry/Textarea.vue, src/Components/DataEntry/index.js, stories/DataEntry/FormGroup.stories.mdx, stories/DataEntry/Textarea.stories.mdx
=> [change] TextArea -> Textarea

vue.config.js
=> [add] dom7, swiper to transpileDependencies

src/Components/Message/Modal/FullscreenModal.vue, stories/Message/Modal/FullscreenModal.stories.mdx
showCloseButton false일 때 header 영역 추가
=> [add] fullscreenmodal align type

src/Components/Message/Modal/AlertModal.vue, src/Components/Message/Modal/Modal.vue, src/Components/Message/Modal/PermissionModal.vue
- Modal에서 전역 적용되어있던 width: 100% 제거
- min-width 추가
- PermissionModal content영역 min-height, max-height 추가
=> PermissionModal min-height, max-height 추가, Modal width 100% 전역 제거 

src/Components/Etc/TellingAvatarQuote.vue, src/Components/index.js
- export Etc folder
- 아바타 영역에 padding-x 8px 추가
=> [add] TellingAvatarQuote 수정 (export, style)

src/Components/DataEntry/Select.vue, stories/DataEntry/Select.stories.mdx
- Select option이 label, value 구조일 경우, label 보여주기
- option이 label, value인 mdx 예제 추가
- validator object 추가
=> Select option이 label, value 구조일 경우 label 보여주기, mdx 추가

src/Components/Etc/TellingAvatarQuote.vue
pc에서 말풍선 꼬리와 아바타가 수평이 안 맞아서 수정
=> [fix] TellingAvatarQuote style 오류 수정

src/Components/DataEntry/Select.vue
- Select option 글자색 추가 (gray800) 
- 외부에서 value를 바꾸는 경우에도 label 로직이 적용되도록 변경
=> [add] Select option 글자색 추가 (gray800), label 로직 변경

src/Components/DataEntry/TextField.vue, stories/DataEntry/Textfield.stories.mdx
boolean type
- true: autocomplete="on"
- false: autocomplete="off"
=> [add] TextField autocomplete prop

assets/style/base/utils.scss
- break-normal
- break-word
- break-all
=> [add] word break util style

src/Components/DataDisplay/Swiper.vue, stories/DataDisplay/Swiper/SwiperItemExample.vue
laravel에 반영하려니까 swiper 배경이 보여서 수정하게 되었습니다
=> [change] .swiper 배경 색상 -> swiperItemExaple에 추가하였습니다

src/Components/DataDisplay/EduCard.vue, stories/Card/Card.stories.mdx
title 문구가 넘칠(2줄 이상)경우 ...처리 추가함
=> [add] EduCard style 추가

src/Components/DataDisplay/Tabs.vue
- active slide의 위치가 left에 고정인 것을 해제
=> [fix] tabs

src/Components/Button/Button.vue
=> [fix] Button primary-text-color 변경 (green800 -> green600)

assets/style/base/color.scss, src/Elements/Core/Colors/index.js
- remove yellow700
- add yellow600
- fix red000
=> [change] colors

src/Components/DataDisplay/Hint.vue, src/Components/DataEntry/DatePicker.vue, src/Components/DataEntry/TextField.vue, stories/DataEntry/InputGroup.stories.mdx
- Hint
- value prop -> slot으로 변경
- 세로 가운데 정렬 스타일 제거
- InputGroup
- Hint 스토리 예시 추가
=> Hint slot으로 변경, InputGroup Hint 예시 추가

src/Components/DataDisplay/EduCard.vue, stories/Card/Card.stories.mdx
eduCard title 에 bold 형태의 텍스트가 들어갈 경우에 대처하기 위하여 props로 받아오던 title을 slot 형태로 변경
=> [change] eduCard title props를 slot형태로 변경

src/Components/DataDisplay/EduCard.vue, stories/Card/Card.stories.mdx
Reverts comento/comento-ui#424
develop에 merge되어야 하는데 master에 되었습니다.
=> Revert "[change] eduCard title props를 slot형태로 변경"

src/Components/DataDisplay/EduCard.vue, stories/Card/Card.stories.mdx
=> [fix] title slot default layout setting (typography)

src/Components/DataDisplay/EduCard.vue
=> [add] card hover interaction

src/Components/DataDisplay/EduCard.vue
eduCard position 변경 된 부분 과 hover 부분을 다른 브랜치로 작성해서 합쳤더니 크리티컬한 오류가 발생했네요 .. :( 
다시 한번 배포 부탁드립니다.. 하핫..
=> [fix] hover 애니메이션 position 변경

assets/style/base/utils.scss, src/Components/DataDisplay/EmptyBox.vue, src/Components/DataDisplay/index.js, stories/DataDisplay/EmptyBox.stories.mdx
https://www.figma.com/file/1cr43gokh0m1dlS3rm5L7z/comento-design-system?node-id=5949%3A1
피그마 상에서 empty 파트입니다.
=> [add] EmptyBox 컴포넌트 추가

src/Components/DataDisplay/Chip.vue, stories/DataDisplay/Chip.stories.mdx
figma 상에는 존재하나 아직 개발이 되지 않은 chip type을 추가했습니다.
=> [add] add chip type

src/Components/DataDisplay/EduCard.vue
caption 사이 divider가 나오지 않고 있어서 고치면서 Divider컴포넌트로 바꿨습니다.
=> [fix] eduCard caption divider

src/Components/DataDisplay/Swiper.vue, stories/DataDisplay/Swiper/Swiper.stories.mdx
더 좋은 네이밍이 있다면 알려주시오!
centeredSlides 값은 swiper에서 똑같이 가져왔어요
=> [add] swiper centeredSlides 옵션 추가

src/Components/DataDisplay/Swiper.vue, stories/DataDisplay/Swiper/Swiper.stories.mdx
duplicate된 slide에 @click-slide로 listener를 전달하기 위함
=> [fix] event listeners binding

src/Elements/Core/Colors/index.js, stories/Callout/Callout.stories.mdx
=> [add] gray250

src/Components/DataDisplay/Drawer/Drawer.vue, src/Components/DataDisplay/Drawer/SideDrawer.vue
- pc, mobile width 디자인과 달라서 변경
- height에서 header 높이를 차감하도록 변경
=> SideDrawer width, height 변경

assets/style/base/animation.scss, src/Components/DataDisplay/Drawer/Drawer.vue, src/Components/DataDisplay/Drawer/SideDrawer.vue, src/Components/DataDisplay/Drawer/SideDrawerExample.vue
- **Drawer** 켜져있을 때 외부 스크롤 막기
- **SideDrawer**
- 인터랙션 변경
- align 속성에서 `up`, `down` 제거
=> SideDrawer 변경 (align props 변경, 인터랙션 추가, 외부 스크롤 막기 추가)

src/Components/DataDisplay/Swiper.vue
=> [remove] swiper spacing 제한 해제

src/Components/DataDisplay/EduCard.vue
=> [change] eduCard 모바일일 때, 썸네일 높이 120px로 변경

src/Components/DataEntry/Select.vue, stories/DataEntry/Select.stories.mdx
- **size: small, medium(default)**
- **size에 따라 아이콘의 color가 달라짐** -> `color` default를 **null**로 하고, computed에서 color 값이 null일 경우 **size별 color를 지정**
=> [add] Select size prop, update mdx docs

assets/style/base/mixins.scss, src/Components/Button/Button.vue
난잡해지는 코드를 어찌할까 하다가 mixin을 쓰니 해결됐네요. 무야호~!
=> [add] Button 모바일에서는 active, focus 스타일 제거

src/Components/DataDisplay/Tabs.vue
1. 밑줄이 항상 보이도록 변경 (원래는 basic type에만 있었음)
2. 밑줄색 변경 (gray200)
=> [change] Tabs swiper 밑줄 기본으로 변경, 밑줄색 변경(gray200)

src/Components/DataDisplay/Content.vue, stories/DataDisplay/Content.stories.mdx
1. Content 리팩토링
- margin 인라인 클래스 -> 각 클래스에서 처리
- overline margin-bottom 6px로 변경 (디자이너 요청)
2. docs 개선
- 콘텐츠는 Box로 감싸야한다는 문구 추가
- 예시 컴포넌트 개선
=> [change] Content 리팩토링, docs 개선

src/Components/DataDisplay/Content/ProfileWithText.vue, src/Components/DataDisplay/Content/index.js, stories/DataDisplay/Content.stories.mdx, stories/DataDisplay/Content/ProfileWithText.stories.js
=> [add] ProfileWithText 컴포넌트, 스토리북 추가

assets/style/base/normalize.scss
Reverts comento/comento-ui#536
=> Revert "[remove] ios에서 input shadow가 들어가는 이슈 해결"

src/Components/Message/Popover.vue, src/Components/Message/Tooltip.vue
flip속성 말고도 다른 속성도 변경할 수 있어야 해서 popperOptions 전체를 받으려고 합니다.
=> [change] popperOptions를 받을 수 있도록 변경

src/Components/DataEntry/Rating/RatingGroup.vue
=> [fix] RatingGroup 여백 변경

src/Components/DataEntry/Select.vue, stories/DataEntry/Select.stories.mdx
disabled 속성을 추가함
label까지 disabled 스타일을 주어야 하는지는 확정되지 않아서 일단 select box 영역만 처리함
(디자이너님께 물어보니 실제로 사용할 일이 생길 때 확정할 수 있을 것 같다고 함)
=> [change] Select disabled 속성 추가

src/Elements/Utility/Overlay.vue
persistent면 esc로 꺼지면 안돼서 오류를 수정함
=> [fix] Overlay persistent true여도 esc로 꺼지는 오류 수정

src/Components/DataDisplay/Avatar.vue, src/Components/DataDisplay/Content/UserInformation.vue, src/Components/DataDisplay/Content/index.js, stories/DataDisplay/Avatar.stories.mdx, stories/DataDisplay/Content/UserInformation.stories.mdx
=> UserInformation 추가

src/Components/DataDisplay/Content/UserInformation.vue, stories/DataDisplay/Content/UserInformation.stories.mdx
1. prop명 변경
size -> type(simple, normal, full)
커뮤니케이션이 용이하도록 디자인에서 사용하는 명칭으로 바꿨습니다.
2. 스타일 수정
아이콘 여백 디자인이 변경됐습니다.
=> UserInformation prop, 스타일 수정

src/Components/DataDisplay/Content/UserInformation.vue
컴포넌트의 기본 여백을 통일하고, 사용할 때 추가 여백을 주는 것으로 변경 (Reply 확장성 고려)
=> [change] UserInformation 기본 padding 2px 0으로 변경

src/Components/DataDisplay/Content/UserInformation.vue, src/Components/DataDisplay/Reply.vue, src/Components/DataDisplay/index.js, stories/DataDisplay/Reply.stories.mdx, utils/nl2br.js
- **user-information**: UserInformation 컴포넌트는 slot으로 전달하는 항목이 많아서 확장성을 위해 slot으로 구역만 만들어두었습니다.
- **value**: 댓글 내용
- `string`
-  v-html, nl2br 내부에 적용했습니다.
- **date**: 날짜
- `string`
- 사용하는 곳마다 dateFormat이 다를 것이기 때문에 string형식으로 만들었습니다.
- **clickReportButton**: 신고 버튼 클릭 이벤트입니다.
=> Reply 컴포넌트

src/Components/DataEntry/Select.vue
외부에서 값을 주입해도 label이 안 바뀌는 현상이 있어서 @input 이벤트를 추가했습니다.
=> [fix] Select @input 추가

src/Components/DataDisplay/Reply.vue, stories/DataDisplay/Reply.stories.mdx
내 댓글은 신고 버튼이 안 보여야 하기 때문에 추가했습니다.
=> [fix] Reply showReport prop 추가

src/Components/DataDisplay/Content/UserInformation.vue, stories/DataDisplay/Content/UserInformation.stories.mdx
=> [fix] normal, full type에서 company없이 사용하는 경우 대응

src/Components/DataEntry/Select.vue
클릭할때는 input event만 emit -> value가 바뀌면서 watch value의 handleSelect를 실행
코드로 value를 바꾸면 value의 handleSelect를 실행
=> [fix] value를 코드로 변경했을 때 label 반영안되는 이슈 해결

src/components/components/dataDisplay/chips/Chip.vue, stories/components/dataDisplay/Chip.stories.mdx
=> feat(change): Chip isHover prop 제거

src/components/components/dataDisplay/list/fileList/FileItem.vue
=> [remove] 수정 시 파일 이름 왼쪽 아이콘 제거

src/assets/style/tooltip/common.scss, src/components/components/message/Popover.vue, src/components/components/message/Tooltip.vue, src/utils/constants/tooltip.js, stories/components/message/Popover.stories.mdx, stories/components/message/Tooltip.stories.mdx
=> feat(change): Tooltip, Popover top props 추가

src/components/components/dataEntry/input/TextField.vue
type을 number로 해도 value default가 ''라서 오류 발생
=> fix: TextField number type validation 오류 수정

src/components/components/message/modal/BasicModal.vue, src/components/components/message/modal/WithFormModal.vue, stories/components/message/modal/WithFormModal.stories.mdx
변경 이유:
- 커스텀 컬러 변경이 잦아서 side effect가 발생할 수 있음
- 버튼 내 Loader는 커스텀 style로 컨트롤할 수 없음
=> feat: WithFormModal, BasicModal에 buttonColor props 추가

src/assets/style/base/color.scss, src/components/components/dataEntry/DatePicker.vue, src/components/components/dataEntry/RadioButton.vue, src/components/components/dataEntry/input/TextField.vue, src/components/components/general/button/Button.vue, src/utils/constants/color.js
회의했던 color name 확정안을 반영합니다.
https://www.notion.so/comento/74908ef5967a4a28874609078eecd8cb
=> Feature/add colors (우선순위 상)

src/components/components/other/Loader.vue, stories/components/other/Loader.stories.mdx
LoaderColors = buttonColors로 해놓고 LoaderColors를 import해서 사용하면 인식하지 못함. 왜인지 모르겠음.
=> fix: loader story 오류 수정

src/assets/style/base/color.scss, src/components/components/general/button/NarrowButton.vue, stories/components/general/button/NarrowButton.stories.mdx
- 스토리에서 gray500 -> gray400으로 변경 (피그마랑 통일)
- transparent 옵션 추가
=> feat: NarrowButton 리뉴얼

src/components/components/dataEntry/Checkbox.vue
checkbox의 디자인시스템 변경 작업입니다.
- check시 아이콘의 색상 변경 작업
- small, xsmall일때 svg의 크기를 변경하는 작업
- hover, disabled일때의 색상 변경
- checkbox와 label간의 간격 조정
을 진행하였습니다.
=> Checkbox 변경작업

src/components/components/dataDisplay/Swiper.vue, stories/components/dataDisplay/swiper/Swiper.stories.mdx, stories/components/dataDisplay/swiper/SwiperItemExample.vue
=> Swiper 리뉴얼

src/assets/style/base/color.scss, stories/components/general/button/NarrowButton.stories.mdx
=> button transparent hover 배경색 변경

stories/components/dataDisplay/Table.stories.mdx
story에서 secondary 인 부분 info 로만 바꿈
=> fix: secondary to info

src/components/components/dataDisplay/Reply.vue
=> feat: Reply 변경

src/components/components/message/Toast.vue
security type 추가
font-weight 변경
=> feat: Toast 수정사항 변경

src/components/components/dataDisplay/card/PromotionEduCard.vue, stories/components/dataDisplay/card/PromotionEduCard.stories.mdx
=> feat: PromotionEduCard 추가

src/components/components/dataDisplay/chips/Chip.vue, src/components/components/dataDisplay/list/fileList/FileSummary.vue, src/components/components/dataEntry/Textarea.vue, src/components/components/dataEntry/input/TextField.vue, src/components/components/general/button/Button.vue, src/components/components/other/Loader.vue, stories/components/dataDisplay/ChipGroup.stories.mdx, stories/components/dataDisplay/Table.stories.mdx, stories/components/dataDisplay/content/UserInformation.stories.mdx, stories/components/dataDisplay/drawer/SideDrawerExample.vue, stories/components/dataEntry/Dropdown.stories.mdx, stories/components/dataEntry/FormGroup.stories.mdx, stories/components/dataEntry/input/InputGroup.stories.mdx, stories/components/dataEntry/input/Textfield.stories.mdx, stories/components/general/button/Button.stories.mdx, stories/components/general/button/ButtonGroup.stories.mdx, stories/components/message/modal/FullscreenModal.stories.mdx, stories/components/message/modal/WithFormModal.stories.mdx
outlined -> outline
underlined -> underline
=> type명 변경 (outline, underline)

src/assets/style/base/fonts.scss
font weight의 semi bold를 추가하는 작업을 진행하였습니다.
=> feat: font semi-bold 추가

stories/components/dataDisplay/Reply.stories.mdx, stories/components/dataDisplay/card/CoreCard.stories.mdx, stories/components/dataDisplay/content/ProfileWithText.stories.js, stories/components/dataDisplay/content/UserInformation.stories.mdx, stories/components/etc/TellingAvatarQuote.stories.mdx
아이콘 이름을 바꾸면서 기존 코드를 바꾸지 않아서 오류 발생
=> fix: 아이콘 이름 변경

src/components/components/dataDisplay/EmptyBox.vue, stories/components/dataDisplay/EmptyBox.stories.mdx
=> feat: EmptyBox 교체

src/assets/style/base/fonts.scss, src/assets/style/base/mixins.scss, src/assets/style/base/utils.scss, src/assets/style/base/variables.scss, src/assets/style/quill/quill.snow.css, src/components/components/dataDisplay/CustomPagination.vue, src/components/components/dataDisplay/chips/Chip.vue, src/components/components/dataEntry/input/SearchInput.vue, src/components/components/general/button/Button.vue, src/components/components/message/Alert.vue, src/components/components/message/Callout.vue, src/components/elements/core/typography/Typography.vue
- font-weight는 300~600만 사용합니다.
- 이름은 아래와 같습니다.(pretendard의 폰트명을 따름)
- 300: light
- 400: regular(기본)
- 500: medium
- 600: semi-bold
=> feat: font-weight 변경

src/components/components/dataDisplay/Pagination.vue, stories/components/dataDisplay/Pagination.stories.mdx
=> fix: 단방향 바인딩으로 수정

src/assets/style/base/mixins.scss, src/assets/style/base/utils.scss, src/components/components/dataDisplay/EmptyBox.vue, src/components/components/dataDisplay/content/ProfileWithText.vue, src/components/components/dataDisplay/content/UserInformation.vue, src/components/components/etc/TellingAvatarQuote.vue, src/components/components/message/modal/PermissionModal.vue, src/components/elements/core/typography/Typography.vue, stories/components/dataDisplay/card/CoreCard.stories.mdx
=> feat: Typography font-weight props 변경

src/components/components/dataDisplay/Reply.vue, src/components/components/dataDisplay/content/UserInformation.vue
https://www.notion.so/comento/reply-70d462c194e44232ae0be4dfc48022ca
=> feat: Reply QA 반영

src/components/components/other/Loader.vue
https://www.notion.so/comento/loader-2b4968a426844773a6628151b82e77f6
=> feat: info color 변경

src/components/components/dataDisplay/Avatar.vue
https://www.notion.so/comento/avatar-e856d692a45e455ab9cda4cb3d367503
=> feat: logo type background image 변경

src/assets/style/base/utils.scss, src/components/components/dataDisplay/Avatar.vue, src/components/components/dataDisplay/Badge.vue, src/components/components/dataDisplay/drawer/BottomDrawer.vue, src/components/components/dataDisplay/drawer/SideDrawer.vue, src/components/elements/core/typography/Typography.vue
=> feat: Typography font-weight 변경

src/components/components/dataDisplay/rating/TextRating.vue, stories/components/dataDisplay/rating/TextRating.stories.mdx
https://www.notion.so/comento/rating-5737980b446e4314af44d093ab07a5cf
=> feat: 글자색 기본값 넣기

src/components/components/dataDisplay/Swiper.vue
- circle 컨트롤 버튼 그림자 추가
- 속도 6000 -> 5000 낮춤 반영
=> fix: circle 그림자 추가 & 스와이퍼 속도 낮춤 반영

src/components/components/dataDisplay/card/EduCard.vue
=> fix: title font-weight 수정

src/components/components/dataDisplay/Swiper.vue
적절한 time 정해지면 머지하겠습니다 (지금 타임 조정중)
=> fix: 스와이퍼 5000 -> 3000변경

src/components/components/general/button/Button.vue, stories/components/general/button/Button.stories.mdx
- fill loading시 보더부분이 얇게 나옴 수정
- 화면 노출 간격있게 보이도록 반영
=> fix: button qa

src/components/components/general/button/Button.vue
large일 때 bold -> 600
xlarge일때 bold -> 400
=> fix: font-weight 수정

src/components/components/etc/TellingAvatarQuote.vue
display: flex !important 때문이라서 v-if로 변경
=> fix: 모바일에서 이름 나오는 오류 수정

src/components/components/general/button/IconButton.vue, stories/components/general/button/IconButton.stories.mdx
button type이 없으면 submit이 기본이라서 form이 제출됨
button컴포넌트도 추후 대공사 필요
=> feat: iconButton type props 추가

src/components/components/dataDisplay/chips/Chip.vue
nuxt에서만 폰트 수평이 안 맞는 문제의 임시방편 해결
=> feat: Chip small에 line-height 16px 추가

src/components/components/dataDisplay/Tabs.vue
=> fix: Tabs 모바일 버튼 스타일 오류 수정

src/assets/style/quill/quill.init.scss
오류 상황
폰트가 바뀌면서 스타일이 깨져서 기존에 있던 top 수치를 없앴습니다.
=> fix: 에디터에서 글자크기 label 스타일 오류 수정

src/assets/style/base/mixins.scss
[채림님 요청](https://comento.agit.io/g/300257914/wall/328683741) 참고
=> feat: body1 letter-spacing 변경

src/components/components/message/Banner.vue, stories/components/message/Banner.stories.mdx
Banner 컴포넌트에 모바일일 때 버튼이 보이게 추가
https://www.figma.com/file/cHjLshiQwSZSjZ79aJWZJk/NEW-design-system?node-id=72%3A3666
=> feat: Banner 모바일 버튼 추가

src/components/components/message/Banner.vue
모바일에서 margin-bottom: 20px 적용한걸 PC에서 초기화를 안해서 수정
=> fix: 모바일 여백이 PC에 적용된 오류 수정

src/components/components/dataDisplay/EmptyBox.vue
https://comento.agit.io/g/300257914/wall/328961546
=> feat: EmptyBox background 제거

src/components/components/message/Banner.vue
Reverts comento/comento-ui#865
=> Revert "fix: 모바일 여백이 PC에 적용된 오류 수정"

src/components/components/dataDisplay/EmptyBox.vue
EmptyBox 버튼을 링크 처리만 해놔서 이벤트를 사용 가능하게 변경
=> feat: EmptyBox 버튼 클릭 이벤트 추가

src/components/components/dataDisplay/chips/Chip.vue
outline type과 fill type width를 맞추기 위함
=> feat: chip box-sizing 변경

package.json, src/assets/style/base/color.scss, src/assets/style/base/utils.scss, src/components/components/dataDisplay/Reply.vue, src/components/components/dataDisplay/content/Content.vue, src/components/elements/core/typography/Typography.vue, yarn.lock
- linkify 추가
- 하이퍼링크 스타일 적용
- 링크 색상 변경
- Reply, Content, Typography 컴포넌트에 하이퍼링크 적용
=> feat: Reply, Content, Typography에 하이퍼링크 적용

stories/elements/utility/Divider.stories.mdx
=> feat: test commit

src/components/components/dataDisplay/list/alarmList/AlarmList.vue, stories/components/dataDisplay/list/alarmList/AlarmList.stories.js
AlarmList에서 선을 없애는걸로 디자인이 변경됐습니다.
=> feat: AlarmList에서 Divider 제거

src/components/components/message/modal/FullscreenModal.vue, stories/components/message/modal/FullscreenModal.stories.mdx
- 스토리 개선
- 외부에서 close할 때 인터랙션 안 되는 오류 수정
=> fix: FullscreenModal 인터랙션, 스토리 개선

src/components/components/dataDisplay/list/fileList/FileList.vue
=> feat: FileList spacing 제거

src/components/components/dataEntry/Select.vue
Select의 small 크기가 제대로 적용되지 않던 문제 수정
=> fix: Select small 사이즈 제대로 적용 안된 문제 수정

src/components/components/general/button/NarrowButton.vue
=> fix: NarrowButton icon 수평 맞추기

src/components/components/dataDisplay/Swiper.vue, stories/components/dataDisplay/swiper/Swiper.stories.mdx
https://comento.agit.io/g/300257914/wall/330672718
=> feat: indicator color gray 추가

src/assets/style/base/fonts.scss
Light, Regular 만 요~상하게 CORS 오류가 나서
cdn root를 원래 주소 그대로 썻더니 해결..
=> fix: cors 오류로 font root 수정

stories/elements/core/icon/Icon.stories.mdx
=> fix: 스토리에서 아이콘 순서 변경

src/assets/images/icon/small/icon-loading-small-fill.svg, src/components/elements/core/icon/Icon.vue, stories/elements/core/icon/Icon.stories.mdx
=> feat: loading icon 추가

src/components/components/dataEntry/Select.vue
=> fix: small일 때 리스트 폰트 크기 변경

src/utils/constants/color.js
=> fix: link 색상 변경

src/components/components/dataDisplay/content/UserInformation.vue, src/components/components/dataDisplay/content/UserInformationCaption.vue, src/components/components/dataDisplay/content/UserInformationChipGroup.vue, src/components/components/dataDisplay/content/UserInformationCompany.vue, src/components/components/dataDisplay/content/UserInformationName.vue, src/components/components/dataDisplay/content/index.js, stories/components/dataDisplay/content/UserInformation.stories.mdx
UserInformation 에서는 slot 자리만 만들어놓고, 나머지 세부 컴포넌트는 따로 만들어서 자리에 배치하는 식으로 변경. 이렇게 하면 변화에 더 유연하지 않을까 생각이 듭니다.
https://www.figma.com/file/cHjLshiQwSZSjZ79aJWZJk/NEW-design-system?node-id=72%3A8&t=LBUZGxkBrUcUr7Qo-0
=> feat: UserInformation component 변경

src/components/components/dataDisplay/card/EduCard.vue
EduCard가 아직 화면에 없을때부터 이미지를 모두 불러와서 loading=lazy 적용을 위해 추가했습니다
=> feat: EduCard img에 로딩 속성 추가

src/assets/style/base/color.scss, src/utils/constants/color.js, stories/elements/core/color/ColorExample.vue
[요청](https://comento.agit.io/g/300257914/wall/333755008)에 맞춰 컬러 추가
=> feat: gray050 컬러 추가

src/components/components/dataDisplay/drawer/Drawer.vue, src/components/components/message/modal/Modal.vue
=> fix: 닫기 버튼 아이콘 색상 변경

src/components/components/dataDisplay/Avatar.vue, src/components/components/dataDisplay/card/PromotionEduCard.vue, src/components/components/dataDisplay/chips/Chip.vue, src/components/components/dataEntry/RadioButton.vue, src/components/components/message/Alert.vue, src/components/components/message/Banner.vue, src/components/components/message/Callout.vue, stories/components/dataEntry/input/Textfield.stories.mdx, stories/components/general/button/IconButton.stories.mdx, stories/components/message/Alert.stories.mdx, stories/components/message/Banner.stories.mdx
- 아이콘 크기 변경 누락된 것 추가
- 스토리북 오류 수정
=> fix: 오류 수정(아이콘 크기, 스토리북)

src/assets/style/base/fonts.scss
-
cors 때문에 s3주소를 썼지만, 해당 문제를 해결해 볼 예정
=> feat: font에 cdn 주소 추가

src/assets/style/tooltip/common.scss, src/components/components/message/Tooltip.vue, src/utils/constants/tooltip.js, stories/components/message/Tooltip.stories.mdx
=> feat: Tooltip left 방향 추가

src/components/components/dataEntry/Textarea.vue
=> feat: textarea attrs 전달

src/components/components/dataDisplay/Label.vue
스펙이 바뀌어서 변경합니다. 
https://comento.agit.io/g/300257914/wall/334953562
=> fix: Label 스타일 변경

src/components/components/dataEntry/input/SearchInput.vue
medium 사이즈가 없어서 아이콘이 나오지 않는 오류 수정
=> fix: 아이콘이 나오지 않는 오류 수정

src/assets/style/base/mixins.scss, src/assets/style/base/utils.scss
https://comento.agit.io/g/300250333/wall/335678118
=> feat: hide-scrollbar 유틸 함수 추가

CHANGELOG.md, package.json, stories/elements/core/icon/Icon.stories.mdx
=> resolve conflict

CHANGELOG.md
=> resolve conflict(2)

src/components/components/navigation/Header.vue, src/components/components/navigation/TopBar.vue
=> fix: 헤더 로고 오류 수정

src/assets/style/base/color.scss, src/components/components/dataDisplay/Tabs.vue
gray200 -> light-gray(gray100)
https://comento.agit.io/g/300257914/wall/335894963
=> fix: 헤더 내 탭의 divider(border-bottom) 색을 변경

src/components/elements/core/logo/Logo.vue, stories/elements/core/Logo.stories.mdx
Logo의 h1태그 단일 적용으로 인해 SEO 이슈가 발생하여 props로 처리하고, 기본은 div로 사용 되도록 변경 하였습니다.
추가적인 사용성 확장을 위해 h1, div 이외에 h2, span을 추가하였습니다.
=> logo dynamic tag name 적용

src/components/components/navigation/Header.vue
logo type이 기본 div로 변경 되어 h1 태그를 래핑했습니다.
=> logo type 변경

src/components/components/navigation/Header.vue
디자인 - https://www.figma.com/file/dCF2pMcDEzBqv1GBVXZddQ/%ED%97%A4%EB%8D%94%EB%BF%8C%EC%85%94?node-id=3419-76538&t=34m6myXaAwQZhPKB-0
header에 tooltip 추가
=> feat: add header tooltip

src/components/components/navigation/Header.vue
* feat: add header tooltip
* fix: remove header window
=> Feature/add header tooltip (#1066)

src/components/components/etc/TellingAvatarQuote.vue
디자인에 16px로 되어있어서 16px 20px에서 수정
=> fix: TellingAvatarQuote의 모바일 패딩 수정

src/components/components/navigation/SubHeader.vue, stories/components/navigation/SubHeader.stories.mdx
submenu에 새로운 메뉴가 추가될 시, 표시 될 수 있도록 하는 newMenuIndex를 추가함
기본값은 -1로 숫자를 조정하면 표시가 될 수 있도록 함
=> feat: submenu에 새로운 메뉴가 추가될 시, 표시 될 수 있도록 하는 newMenuIndex 추가

src/components/components/navigation/SubHeader.vue, stories/components/navigation/SubHeader.stories.mdx
* feat: submenu에 새로운 메뉴가 추가될 시, 표시 될 수 있도록 하는 newMenuIndex 추가
* fix: 피드백 반영
=> feat: submenu에 새로운 메뉴가 추가될 시, 표시 될 수 있도록 하는 newMenuIndex 추가 (#1075)

src/components/components/navigation/Header.vue
- 업무글: https://comento.agit.io/g/300316830/wall/336941474
일단 관련 코드를 다 없앴고, 실험 결과에 따라 확장성을 부여할게요.
=> feat: Header 내 Tooltip 관련 코드 제거

src/components/components/dataEntry/Dropdown.vue, src/components/components/dataEntry/Select.vue, src/components/components/dataEntry/input/SearchInput.vue, stories/components/dataEntry/Dropdown.stories.mdx
Dropdown에서 input을 제외한 다른 영역을 클릭시 dropdown state가 false가 되는 상황을 수정하고, 클릭 가능 영역을 리스트 내부로 확장하는 작업을 진행하였습니다.
반영 예정은 확정이 아니지만, 검토하기 좋도록 PR로 올리겠습니다.
=> Dropdown내부에서 클릭시 list가 사라지지 않도록 변경

package.json, src/components/components/navigation/SubHeader.vue, stories/components/navigation/SubHeader.stories.mdx
- feat: SubHeader a tag, target 지정 변경
- chore: 배포 명령어 추가
SubHeader에서 isNuxt props 하나로 nuxt-link 또는 a tag를 지정하다보니 메뉴별로 지정이 불가능해서 방식을 변경
=> feat: SubHeader a tag, target 선택

src/components/components/dataEntry/Select.vue
select error 상태일때, 내부 input text도 함께 error 색으로 변경 되도록 수정하였습니다.
=> select - error 컬러 변경

src/assets/style/base/init.scss
comento-libs에서 설명한 [Font smoothing](https://github.com/comento/comento-libs/tree/main/packages/tailwind-plugin#%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8%EC%9D%98-%EC%A3%BC%EC%9A%94-%EB%B3%80%EA%B2%BD%EC%A0%90) 관련 내용을 Vue 프로젝트에도 적용하기 위한 수정 사항입니다.
=> feat: font-smoothing 적용

src/components/components/dataEntry/input/SearchInput.vue
Search input의 pc 규격 변경 요청으로 변경 작업을 진행합니다.
모바일은 그대로 유지됩니다.
=> search input pc 규격 변경

src/components/components/dataDisplay/Badge.vue
=> refactor: Badge 코드 변경

src/components/components/dataDisplay/Badge.vue
=> fix: Badge text가 왼쪽으로 쏠려보이는 오류 수정

src/components/components/message/Toast.vue
바텀네비 및 하단 CTA등과 겹치지 않게(+native 컴포넌트) 현정님 요청에 따라 수정합니다. https://comento.agit.io/g/300257914/wall/346241675
=> feat: toast mobile bottom 위치 수정

scripts/generate-component-index.js
=> fix: 스크립트 오류 수정

src/assets/style/base/init.scss, src/assets/style/base/variables.scss
스크롤바가 좁다는 창섭님, 디자이너의 의견 + next 프로젝트와 통일성을 맞추기 위해 스크롤바 커스텀 스타일을 제거합니다.
참고글
- https://comento.agit.io/g/300257914/wall/343405169
- https://comento.agit.io/g/300250349/wall/345528873
=> feat: 스크롤바 커스텀 스타일 제거

package.json, src/mixins/scrollMixin.js, yarn.lock
Radix를 참고해서 관련 라이브러리를 추가하고 스크롤을 막는 작업 방식을 변경했습니다. Modal, SIdeDrawer, BottomDrawer에 적용됩니다. 혹시 다른 데서 또 쓰이고 있으면 알려주세요.
As-is
https://github.com/user-attachments/assets/cad16030-ab54-4c94-9fcc-29502fca37a9
To-be
https://github.com/user-attachments/assets/9a35c1ce-0e06-4727-bbc7-c254b640db8f
=> fix: 스크롤 없앨 때 덜컹거리는 현상 수정

src/mixins/scrollMixin.js
라이브러리 설명을 참고해서 iOS에서 이용할 수 있게 allowTouchMove 옵션을 추가했습니다.
=> fix: iOS에서 사용할 수 있게 allowTouchMove 옵션 추가

src/components/drawer/Drawer.vue, src/components/modal/Modal.vue, src/mixins/scrollMixin.js
=> fix: body-scroll-lock allowTouchMove 범위 수정

src/components/chips/Chip.vue, stories/components/dataDisplay/Chip.stories.mdx
https://comento.agit.io/g/300257914/wall/347071764
1. color=primary, type=fill  배경 컬러 blue050으로 변경
2. color=error, type=fill 배경 컬러 red050으로 변경
3. 각 chip에 with icon 프로퍼티 추가 (none, left, right)
4. icon이 추가됨에 따라서, 좌,우,상,하 및 간격 여백 조정
=> feat: chip 컴포넌트 수정 반영

src/components/navigation/header/Header.vue
https://github.com/comento/comento-libs/pull/104 같이 반영되어야 하는 친구입니다!
=> feat: /edu에 따른 next화가 되어 menu마다 nuxt값을 확인하여 링크 이동할 수 있도록 변경

src/components/button/Button.vue, src/components/loader/Loader.vue
- info일 때 gray500 -> gray600으로 변경합니다.
- white 색상은 사용하지 않습니다.
- mounted 이후에도 색상 변경에 대응할 수 있게 watch method를 추가했습니다. (ref를 건드리는 거라 immediate를 사용하지는 않았습니다)
=> feat: Loader 컴포넌트 색상 관련 수정

src/components/input/SearchInput.vue, src/components/input/TextField.vue
https://comento.agit.io/g/300257914/wall/354536019#comment_panel_354547882
=> feat: 여백 변경(우측 요소 있을 때, SearchInput)

src/components/input/SearchInput.vue
https://www.figma.com/design/cHjLshiQwSZSjZ79aJWZJk/NEW-design-system_comento?node-id=360-14973&t=JG3OZG2revPunXFe-0
=> fix: 검색창 닫기 아이콘 색상 변경
