src/DataEntry/SearchInput.vue

hideSearchDown method가 v-click-outside directive에 걸려 있습니다. 해당 element가 가려져 있는 경우에도 외부 영역을 클릭 시 의도치 않게 event가 emit됩니다. 따라서 showSearchDropdown이 true일때만 해당 event가 emit하도록 수정하였습니다.

[fix] update:showSearchDropdown event가 계속 emit되는 이슈 해결

---

src/Components/Message/Modal/WithFormModal.vue
src/DataEntry/Input.vue

- **Input** className 변경
- **WithFormModal** Input className 변경 대응
- **WithFormModal** 문단 여백 제거
- 폼을 다양하게 사용할 상황이 많은데, 문단별 여백 때문에 사이드이펙트가 발생하므로 제거함. (디자이너와 협의 완료)
- `클래스룸 제출합니다 모달`에 여백 추가해주세요 @donghoon-song

Input, WithFormModal 변경

---

src/Components/DataDisplay/Avatar.vue

[fix] Avatar background-size 100% 100%로 변경

---

src/Components/Message/Toast.vue

- 오류: width가 고정된듯 텍스트가 두줄이 되는 현상
- 해결: width: fit-content는 IE에서 사용할 수 없어 display: table로 대체
참고
https://m.blog.naver.com/PostView.nhn?blogId=zimny327&logNo=221335293395&proxyReferer=https:%2F%2Fwww.google.com%2F

[fix] Toast width 오류 수정

---

.github/workflows/storybook-deployer.yml

스토리북 배포 시 token이 포함되어 배포되는 문제를 해결했습니다. (github action으로 옮기고 token을 secret에서 불러옴)
배포할 때 shipjs랑 같이 병행으로 실행됩니다.

Feature/add storybook deployer GitHub action

---

assets/style/base/color.scss
assets/style/base/utils.scss
src/Components/Button/Button.vue
src/Elements/Core/Colors/index.js
src/Elements/Core/Icon/Icon.vue
stories/Button/Button.stories.mdx

- color gray -> secondary로 변경
* [change] Icon spinner error color
* [change] xlarge일 때만 icon margin 4px로 변경
* [change] TextButton font-weight normal로 변경
* [change] Button 코드 개선
* [change] Button docs 개선
* [add] Button fixed, absolute props 추가
* [add] Button shadow props 추가
* [change] Box hasShadow -> shadow
* Revert "[change] Box hasShadow -> shadow"
This reverts commit e282a4be2c3f458553b765fbd35bc96a010006b5.
Co-authored-by: donghoon-song <thdehdgns@gmail.com>

Button 개선 (#169 원복), color gray -> secondary로 변경

---

src/Components/Message/Modal/FullscreenModal.vue
stories/Message/Modal/FullscreenModal.stories.mdx

- validator 추가
- 코드 개선
- pc close button style 변경(`top: 12px; right: 12px;`)
- mdx에서 content padding 추가 (스토리북 사용자들이 오류라고 인식할까봐 추가했으며, 실제로는 padding이 없어요.)

FullscreenModal 개선

---

plugins/index.js
plugins/vue-awesome-swiper.js
src/Components/DataDisplay/Swiper.vue

[fix] swiper.css에 있는 변수를 못 불러오는 이슈 해결

---

src/Components/Message/Modal/BasicModal.vue

[add] BasicModal content margin - not br 추가

---

.github/workflows/chromatic-develop.yml

develop에 merge되면 develop에서 storybook을 빌드합니다.
자동으로 하지 않기 때문에 pr의 ancestor가 예전 develop 빌드결과에 머물러서, 동기화가 안되는 이슈를 해결하려고 합니다.

[add] build chromatic on develop

---

src/Components/Message/Modal/Modal.vue
src/Elements/Utility/Overlay.vue

앗 feature 오타.....
modal.vue 안에 handleNotScroll을 추가하고
overlay안에 있었던건 지웠습니다. -> modal과 함께 사용하기 떄문에 중복으로 주기보다는 modal에 추가하였습니다.

[fix] modal handleScroll 수정

---

src/Components/DataEntry/DatePicker.vue

- 캘린더 width를 TextField와 동일하게 하기
- TextField width가 캘린더 기본 width(248px)보다 크면 기본 height(224px)를 1.2배 늘리기

[add] DatePicker 캘린더 width 100%, height 조정

---

src/Components/DataDisplay/Badge.vue

이미 적용된 곳(헤더 알림 뱃지)에서 스타일이 깨져서 `inline-flex`로 변경합니다.

[change] Badge absolute class display inline-flex로 변경

---

src/Components/Message/Callout.vue

Callout close 버튼 position, icon style mixin으로 변경

---

src/Components/Message/Callout.vue
stories/Callout/Callout.stories.mdx

1. Callout에 icon의 자율성이 필요한 상황이 생겨서 Icon slot이 없을 때는 기존 아이콘, 있으면 slot이 나오도록 변경했습니다.
2. slot icon에 margin을 추가하면 아이콘이 짤리는 현상이 있어서 `overflow: inherit`를 추가했습니다.

[add] Callout icon slot, mdx 추가

---

src/Components/Message/Callout.vue

- message영역 `white-space: normal` 추가  (탭 영역이 공백으로 잡히는 이슈)
- 왼쪽 icon `cursor: auto` 추가 (클릭 이벤트가 없는데 포인터 커서로 보이는 이슈)

Callout css 추가

---

src/Components/DataEntry/TextField.vue
stories/DataEntry/Textfield.stories.mdx

- `.active` 하위 `:focus` 때문에 색상이 적용 안 되는 오류
- `persistentHint` props 추가
- `focus` props 제거
- hint 로직 개선 (`hint`가 있고 `persisteneHint`거나, focus되어있거나, `active`인 경우)
- validate mdx 스토리 추가

TextField active color 오류 수정 및 로직개선(hint, focus 로직 개선) 및 persistentHint props 추가

---

src/Components/DataEntry/Select.vue

created에서 처리하면 props가 변경되는 (ex. computed props) 상황에서 적용이 안됨

[fix] created 로직을 watch로 이동

---

src/Components/DataDisplay/Table.vue
src/Components/DataDisplay/index.js
stories/DataDisplay/Table.stories.mdx

- **유연하게 사용**하기 위해 대부분의 구조를 slot으로 나누었으며, props는 최소화했습니다.
- 테이블 각종 여백, head영역의 글자 크기와 색상은 고정값입니다. (디자이너 컨펌 완료)
- 모바일에서 공간이 충분치 않을 경우, PC에서만 디자인시스템을 사용하며 모바일은 따로 코딩합니다.
slot은 총 3개입니다. (head, body, empty)
- head: 테이블 타이틀 영역입니다.
- body: 테이블 콘텐츠 영역입니다. (* **ul > li 구조로 작업**해야 합니다.)
- empty: 테이블 콘텐츠가 없을 때 노출되는 영역입니다.
- cursor: 테이블 콘텐츠 영역 row에 대한 커서 모양입니다. (default, pointer)
1. align: 기본은 center이고 left, right를 사용하려면 특정 태그에 class를 추가합니다. (`text-left`, `text-right`)
2. 클릭이벤트: 특정 태그내에서 @click으로 사용합니다. (`<li @click="클릭이벤트">콘텐츠</li>`)
3. 특정 컬럼의 width: 특정 태그에서 style을 추가합니다.
궁금한 점이 있다면 멘션하여 댓글 달아주세요.

[add] Table 컴포넌트, mdx 추가

---

src/Components/DataEntry/Checkbox.vue
stories/DataEntry/Checkbox.stories.mdx

size prop: string (xsmall, small, medium)
size는 label Typography type에 영향을 준다. (xsmall: caption1, small: body2, medium: body1)
텍스트랑 체크박스 위치잡는게 까다로워서 size별로 하드코딩 되어있는데, 개선가능할 지 피드백 부탁드려요!

Checkbox size prop (xsmall, small, medium)

---

src/Components/DataDisplay/List.vue

margin-bottom -> margin y영역으로 바꿨습니다.

[fix] List margin

---

src/Components/DataEntry/Select.vue

초기 렌더링 시에도 input event를 emit하기 때문에 부모 input event handler가 두번 trigger되는 현상 수정

[fix] 초기 렌더링 시에는 input event emit 방지

---

src/Components/Button/LinkButton.vue
stories/Button/LinkButton.stories.mdx

to 속성을 사용하지 않을 때, `Uncaught SyntaxError: Unexpected token ')'` 오류가 발생해서 괄호 안에 0을 추가했습니다.

LinkButton to 속성이 없을 때 콘솔 오류 수정

---

assets/style/quill/quill.init.scss

사용방법: `<div class="ql-editor ql-editor-content">내용</div>`
`.ql-editor`에 있는 스타일 때문에 VED의 UI가 영향을 받고 있음
```scss
.ql-editor {
min-height: 100px; // 추가 스타일
height: 100%; // 기본 스타일
}
```
- 현재 `.ql-editor`에 적용된 스타일은 그대로 유지한다.
- `.ql-editor`에서 `height: 100%`를 제거하지 않는다.
기본 스타일이며, 딱히 없앨만한 이유가 없다.
- `.ql-editor`에서 `min-height: 100px`를 제거하지 않는다.
모든 에디터에 최소 높이가 있는 것이 우리가 원하는 사양이기 때문이다.
- 에디터 콘텐츠를 위해 추가 클래스(`.ql-editor-content`)를 사용한다.
```scss
.ql-editor {
&-content {	
min-height: auto;
height: auto;
}
}
```
```html
<div class="ql-editor ql-editor-content" />
```

quill-editor 커스텀 스타일 코드 추가 (콘텐츠용 스타일, header 한글화)

---

src/Components/Message/Callout.vue

현재는 close button을 누르면 callout의 click listener까지 발동되는데
수정 버전은 close listener만 실행

[fix] callout 전체에 대한 click event가 close button에도 전달되는 것을 방지

---

src/Components/Layout/NewGrid.vue

모바일에서 `max-width: 375px`로 고정되어있어서 iPhone 6/7/8 Plus에서는 양쪽여백이 넓게 잡힘
`max-width: 100vw`로 변경

[change] NewGrid max-width: 100vw로 변경

---

src/Components/DataDisplay/List/List/ListItem.vue

알람리스트를 제외한 모든 list Item은 사이즈 관계 없이 좌우 패딩을 하나의 수치로 고정하도록 변경

[change] ListItem padding-x 4px로 변경

---

src/Components/DataDisplay/Avatar.vue

flex를 사용하면 아바타가 탈출하는 오류가 있어서 수정합니다.

[fix] Avatar height가 클 때 레이아웃 깨지는 오류 수정

---

src/Components/Button/Button.vue
src/Components/Other/Loader.vue

- secondary 디자인 색상이 변경됨
- 패턴화가 가능한 색상은 변수로 만들고, 불가능한 색상은 오리지널 색상 변수를 활용

[change] Button secondary color 변경

---

src/Components/DataDisplay/Card/CoreCard.vue

1. 답변 더보기 버튼은 답변이 3개 이상이면 `+ n개 답변 더보기`, 아니면 `+ 더보기`로 노출됩니다.
2. overline에 검색 highlight 함수를 넣어줘야해서 v-html로 변경했습니다.

[fix] CoreCard 답변 더보기 버튼 노출 조건 수정, overline v-html로 변경

---

src/Components/Etc/TellingAvatarQuote.vue

width 375px기준 270px이 맞고 240px은 스토리북에서 더 좁게 보여서 제가 더 좁게 잡았네요

[change] max-width 수치 변경

---

src/Components/DataDisplay/Swiper.vue

이 옵션이 있으면 component가 destroy될 때 inline style을 날려버림.

[change] cleanup-styles-on-destroy false

---

src/Components/Button/Button.vue

important일 필요가 없는데 important가 들어가 있었고, 이로 인해 사이드이펙트가 발생하여 제거함

[fix] Button text class font-weight important 제거

---

src/Components/DataDisplay/Tabs.vue

모바일은 hover가 불가능한데, 배경색이 계속 회색으로 남아있어서 pc에서만 실행되도록 변경함

[change] Tabs hover하면 pc에서만 배경색 바꾸기

---

src/Elements/Core/Typography/Typography.vue

[fix] Typography 띄어쓰기 없는 문장일 때 영역 초과하는 오류

---

src/Components/DataDisplay/Content/UserInformation.vue

icon 왼쪽 여백이 2px 생기면서 스타일 변경이 누락되어 추가했습니다.

[fix] userInformation style

---

src/Components/DataEntry/DatePicker.vue

기존 date picker에서 
append-to-body 가 true로 기본 설정되어있는데,
이렇게 되면 date picker 의 팝업이 떳을 때
nuxt의 외부에 해당 팝업 엘리먼트가 생성됩니다..
따라서 style을 줄 수 없는 이슈가 있어서 false로 수정합니다..
(동훈님이 알려줌)

[fix] date picker append-to-body false

---

src/Elements/Core/Typography/Typography.vue

디자인상으로는 caption1 line-height가 14px인데 13.8로 계산되어 13px로 나오고 있습니다.
line-height가 소수일 경우, 내림되는 현상이 있어서 math함수를 활용하는 mixin으로 변경했습니다.

[fix] Typography font-size, line-height math 함수 활용하는 mixin으로 변경

---

src/Components/DataDisplay/Avatar.vue
stories/DataDisplay/Avatar.stories.mdx

아바타가 유저별로 고유한 색상을 가져야하는 경우가 생겨서 id값을 받아 컬러를 설정하는 작업을 추가했습니다.

[fix] 아바타 id prop 추가 및 color와 연동

---

src/Elements/Core/Logo/Logo.vue
stories/Logo/Logo.stories.mdx

- Logo color가 디자인 시스템 색상이 아니어도 사용할 수 있도록 제한을 없앴습니다.
- 스토리 예시를 추가했습니다.

Logo color 제한 해제, 예시 추가

---

src/components/components/dataDisplay/Swiper.vue

iOS 15.1에서 해당 문제를 해결했고,
device가 없는 경우 swiper 가 동작하지 않는 문제가 생겨 삭제합니다.

fix: ios 15.0 대응 코드 삭제

---

src/components/components/dataDisplay/Badge.vue

Tabs 스토리북 예시에서 Badge inline type 스타일 오류를 발견해서 수정했습니다.

fix: Badge inline type style 오류 수정

---

src/assets/style/tooltip/tooltip.scss

c-tooltip--content-wrapper에 background가 생기면 외부 border-radius를 덮어버리는 문제가 있어 추가

[change] tooltip 내부 wrapper border-radius 추가

---

src/assets/style/base/utils.scss
src/components/components/dataEntry/input/FileInput.vue
src/components/components/general/button/FileButton.vue
stories/components/dataEntry/FileInput.stories.mdx

- 아이콘 우측으로 이동 -> 디자인이랑 다르길래 적용했어요
- buttonText props 추가 -> '파일 첨부하기 (최대 2개)'로 사용하는 경우가 생겼어요 
- disabled props 추가 -> 파일 2개 넘으면 비활성화 시키기 위해 필요해요

feat: FileInput 변경

---

src/components/components/dataDisplay/list/fileList/FileItem.vue

fix: 파일 이름이 길 때 말줄임표 추가

---

src/components/components/general/button/IconButton.vue
stories/components/general/button/Button.stories.mdx
stories/components/general/button/IconButton.stories.mdx

IconButton은 컴포넌트를 따로 분리했습니다.
Button안에 들어가면 너무 지저분하고 불필요한게 많은 것 같다는 판단입니다.
소중한 피드백은 감사합니다.
Figma Component Button에 type Icon 보시면 됩니다.
Story는 Button Story에 합쳤습니다.
https://www.figma.com/file/cHjLshiQwSZSjZ79aJWZJk/%5B%EC%9E%91%EC%97%85%EC%A4%91%5D-NEW-design-system?node-id=111%3A7299

feat: IconButton 추가

---

src/components/components/dataEntry/input/TextField.vue

append영역에는 disabled의 background, cursor가 반영되지 않아서 오류 수정

fix: TextField disabled일 때 append 영역은 style 반영 안 되는 오류 수정

---

src/components/components/dataDisplay/Swiper.vue

swiper 옵션에서 loop가 true일때, 요소들의 옵션이 적용 되지 않는 이슈가 있어,
mounted에서 요소들이 모두 파싱 되는걸 기다린 다음, swiper가 init 되도록 변경 하였습니다.

fix: swiper 요소가 모두 파싱 되고, init 되도록 변경

---

src/components/components/message/Banner.vue
stories/components/message/Banner.stories.mdx

전혀 쓰고 있지 않은 컴포넌트여서 업무 중에 사용한 배너들처럼 만들 수 있게 만들고 예시를 스토리북에 추가했습니다

feat: Banner 변경

---

src/components/elements/core/typography/Typography.vue

linkify때문에 vue click event가 작동하지 않음

feat: Typography에서 linkify 제거

---

src/components/components/dataDisplay/list/list/ListItem.vue

기존에 medium 사이즈 ListItem 상하 패딩이 6px로 되어있던 것을 8px로 수정
참고: https://comento.agit.io/g/300257914/wall/329454145

fix: medium ListItem 상하 패딩 수정

---

src/components/components/dataDisplay/chips/Chip.vue

Chip의 transparent 옵션이 다른 클래스의 background-color에 덮어써져서 important로 최우선 순위로 만들었습니다

fix: Chip transparent 우선순위 변경

---

src/components/components/dataDisplay/list/fileList/FileItem.vue
src/components/components/message/Callout.vue

callout, fileInput등 본문과 아이콘이 함께 들어가는 컴포넌트에서 본문이 길어지면 양측에 있는 아이콘이 축소 되는 이슈가 발생 되었습니다.

본문이 길어질 경우 아이콘이 축소 되는 이슈

---

src/components/components/message/Callout.vue

callout의 close 버튼이 full일때 오른쪽 끝단으로 가지 않는 이슈가 발생하여 수정 작업을 진행하였습니다

callout close버튼 위치 조정

---

.prettierrc
src/components/components/dataDisplay/card/EduCard.vue
src/components/components/dataDisplay/card/PromotionEduCard.vue

사파리에서 transform을 이용한 애니메이션과 overflow: hidden, border-radius를 같이 썼을 때 버그가 있다고 합니다.
확인해보니 PromotionEduCard, EduCard 두 컴포넌트에서 문제를 보여서 수정했습니다.
[이 블로그](https://www.sungikchoi.com/blog/safari-overflow-border-radius)를 참고했습니다.

fix: 사파리 transform 관련 버그 수정

---

src/assets/style/quill/quill.core.css

pre-wrap을 사용하면 실제보다 공백이 더 많이 보이는 이슈.
클래스룸에서 작성한 피드백과 익스턴십에서 작성한 피드백을 과제 디테일에서 봤을 때 다르게 보이는 이슈
https://qa.comenthor.com/classroom/8448

change: ql-editor white-space normal로 변경

---

src/assets/style/base/variables.scss
src/components/components/message/Toast.vue

* feat: Toast mobile에서  position top일 때 위치 변경
-
앱 기준 native topbar에 가려지기 때문에 위치 수정
https://www.notion.so/comento/toast-topbar-topbar-f4a05b4c8a04416aa8b604d6dc806cc3
* fix: 문법 수정
-
* refactor: $topbar-height global variable로 이동
-

Feature/change toast top position (#963)

---

src/assets/style/base/variables.scss
src/components/components/message/Toast.vue

* feat: Toast mobile에서  position top일 때 위치 변경
-
앱 기준 native topbar에 가려지기 때문에 위치 수정
https://www.notion.so/comento/toast-topbar-topbar-f4a05b4c8a04416aa8b604d6dc806cc3
* fix: 문법 수정
-
* refactor: $topbar-height global variable로 이동
-
Co-authored-by: Donghoon Song <32301380+donghoon-song@users.noreply.github.com>

Feature/change toast top position (#963) (#965)

---

src/components/components/dataDisplay/content/UserInformationCompany.vue
stories/components/dataDisplay/content/ProfileWithText.stories.js

fix: 유저프로필에 들어가는 아이콘 사이즈 변경 small -> xsmall

---

src/components/components/dataEntry/input/TextField.vue
stories/components/navigation/SubHeader.stories.mdx

textField의 label이 노출 되지 않는 현상을 수정했습니다.
확인 시점까지 이렇게 노출 되고 있었고
이렇게 변경하였습니다.

textField label이 노출 되지 않는 현상 수정

---

src/components/components/dataEntry/input/SearchInput.vue

SearchInput 컴포넌트를 클릭시, ios에서 줌인이 발생하는 이슈가 제기 되어, font-size를 줌인을 유발 시키지 않는 16px로 변경하고, 그에 맞게 UI 크기를 조정했습니다.
아지트 업무글 : https://comento.agit.io/g/300257914/wall/345447882

SearchInput 폰트 사이즈 및 UI 조정

---

src/components/components/dataDisplay/chips/Chip.vue

xlarge size만 height가 들어가 있지 않아서 수정합니다.
https://comento.agit.io/g/300257914/wall/346240366?ir=true&l=agit_io_user_mentioned_v3&sid=346318901&tid=300166075&ts=1718679743#comment_panel_346318901

fix: Chip xlarge height 수정

---

src/components/chips/Chip.vue
stories/components/dataDisplay/Chip.stories.mdx

- as-is
- to-be
- as-is
- to-be
업무글: https://comento.agit.io/g/300257914/wall/346411376

fix: Chip close button 색상 오류 수정, 스토리북 예시 추가

---

src/components/icon/BaseIcon.vue

기존에 Icon에 cursor: auto가 선언되어있는데 아래 이미지와 같은 현상이 나타납니다.
cursor는 원래 기본값이 auto인데 이걸 선언하면서 자연스럽게 덮어써질 때도 auto로 다시 돌아가서 그런 것 같아서 삭제했습니다.
혹시 이렇게 선언한 히스토리가 따로 있다면 말씀해주세요.

feat: Icon에서 cursor 선언 지우기

---

src/mixins/scrollMixin.js

[Datadog](https://app.datadoghq.com/logs?query=service%3Acomento-nuxt%20status%3Aerror%20%22undefined%20is%20not%20an%20object%20evaluating%22&agg_m=count&agg_m_source=base&agg_q=status%2Cservice&agg_q_source=base%2Cbase&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&storage=hot&stream_sort=time%2Cdesc&top_n=10%2C10&top_o=top%2Ctop&viz=stream&x_missing=true%2Ctrue&from_ts=1727056309320&to_ts=1727661109320&live=true)에서 `undefined is not an object (evaluating 't.dataset.bodyScrollLockIgnore')` 오류가 나는 것을 해결하려는 수정입니다.
TextNode 등으로 dataset이 아예 존재하지 않는 el이 있는 것으로 추정되어, HTMLElement인지 확인하고 dataset도 확인합니다

fix: allowTouchMove에서 오류 발생 수정

---

src/components/drawer/BottomDrawer.vue
src/components/drawer/SideDrawer.vue
src/components/modal/Modal.vue

Modal, BottomDrawer, SideDrawer의 show를 바꾸지 않은 채로 페이지를 넘어가는 등의 경우에는 스크롤을 막는게 풀리지 않아서 beforeDestroy에 추가했습니다.

fix: Modal, BottomDrawer, SideDrawer beforeDestroy 추가

---

src/components/chips/Chip.vue

기존 chip 규격 변경 추가 반영
primary, error 컬러에서 타입과 상태에 따라 800,600 케이스가 있음
L primary, error에서 clickable-fill의 경우 기본적으로 800
L error만 fill인 상타에도 800으로 노출되어야 하는 케이스가 있음
[디자인](https://www.figma.com/design/cHjLshiQwSZSjZ79aJWZJk/NEW-design-system_comento?node-id=72-429&node-type=frame&t=TPtVJNfqt12Yvmjb-0)

chip 수정사항 반영

---

src/components/navigation/subHeader/SubHeader.vue

- 서브헤더의 width 가 100vw로 스크롤 영역까지 포함하고 있어 기존 디자인과 맞지 않는 부분을 수정하였습니다. ( 100vw -> 100% )
**[Before]**
**[After]**
**[`vw` -> `%` 수정에 따른 레이아웃 변화]**

서브헤더 사이즈를 디자인에 맞게 수정
